name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'agda2rust.cabal'
      - 'cabal.project'
      - 'Makefile'
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macOS-latest, windows-latest
        cabal: [3.8]
        ghc:
          # - 8.6.5
          # - 8.8.4
          # - 8.10.7
          # - 9.0.2
          # - 9.2.5
          - 9.4.3
          # - 9.6.3
          # - 9.8.1

    steps:
    - uses: actions/checkout@v3
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - name: Install Haskell
      uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Freeze cabal dependencies
      run: cabal freeze

    - name: Cache cabal store
      uses: actions/cache@v3
      with:
        path:         ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key:          ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build
      run: make build

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2024-06-10

    - name: Setup Rust nightly
      run: rustup default nightly-2024-06-10

    - name: Run test suite
      run: make test

    - name: Generate HTML
      run: |
        sudo apt-get install -y pandoc zsh
        make html

    - name: Deploy HTML
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: test/html
