on: [push]
name: build
jobs:
  cabal:
    name: agda2rust
    runs-on: ubuntu-latest
    steps:
    - name: Checks-out repository
      uses: actions/checkout@v4

    - name: Set up GHC
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: '9.4.3'
        cabal-version: '3.8'
        cabal-update: false

    - run: cabal freeze

    - name: Cache ~/.cabal/store
      uses: actions/cache@v3
      with:
        path:         ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key:          ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build
      run: make build

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Test
      run: make test
